apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DataLocation
metadata: # kpt-merge: /datalocation
  name: datalocation
spec:
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["*"]
  parameters:
    locations:
      - "northamerica-northeast1"
      - "northamerica-northeast2"
      - "global"
    allowedServices:
      - ""
